name: Sync CI Files to Production

on:
  workflow_dispatch:  # Manual trigger

jobs:
  sync-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Copy CI files to production files
        run: |
          # Find all _CI.txt files and copy them to non-_CI versions
          for ci_file in *_CI.txt; do
            if [ -f "$ci_file" ]; then
              # Get the base filename without _CI suffix
              base_file="${ci_file/_CI.txt/.txt}"
              
              echo "Copying $ci_file to $base_file"
              cp "$ci_file" "$base_file"
            fi
          done
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync CI files to production files"
          branch: sync-ci-files-${{ github.run_number }}
          delete-branch: true
          title: "Sync CI files to production"
          body: |
            This PR synchronizes the content from `_CI.txt` files to their production counterparts.
            
            ### Files updated:
            - All `*_CI.txt` files copied to `*.txt` files
            
            **Triggered by:** @${{ github.actor }}
            **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: automated
      
      - name: Summary
        run: |
          if [ "${{ steps.check_changes.outputs.has_changes }}" == "true" ]; then
            echo "✅ Pull request created successfully"
          else
            echo "ℹ️ No changes needed - files already in sync"
          fi
